apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-timescale-ingestor
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-timescale-ingestor
  template:
    metadata:
      labels:
        app: kafka-timescale-ingestor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: ingestor
        image: 192.168.1.221:5001/kafka-timescale-ingestor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: metrics
        envFrom:
        - configMapRef:
            name: kafka-timescale-config
        env:
        - name: TIMESCALEDB_USER
          value: "postgres"
        - name: TIMESCALEDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timescaledb-secrets
              key: password
        - name: METRICS_PORT
          value: "8001"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: metrics
          failureThreshold: 60
          periodSeconds: 10
          timeoutSeconds: 5
          initialDelaySeconds: 20
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  # Send SIGTERM to the Python process
                  kill -TERM 1
                  # Wait for graceful shutdown
                  sleep 10
      imagePullSecrets:
      - name: local-registry-cred
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate