apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trading

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- network-policy.yaml

commonLabels:
  app: kafka-timescale-ingestor
  environment: production

images:
- name: kafka-timescale-ingestor
  newName: 192.168.1.221:5001/kafka-timescale-ingestor
  newTag: latest