apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-timescale-ingestor-policy
  namespace: trading
spec:
  podSelector:
    matchLabels:
      app: kafka-timescale-ingestor
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8001
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kafka
  ports:
  - port: 9092
    protocol: TCP
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP